version: '3.7'

services:
  succubus.space-frontend:
    image: ghcr.io/turbocheetah/succubus.space-frontend:latest
    container_name: succubus.space-frontend
    ports:
      - '3000:3000'
    restart: 'unless-stopped'